CREATE TABLE IF NOT EXISTS item_updates(
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	status VARCHAR(100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users(
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users_item_updates(
	item_update_id VARCHAR(100) NOT NULL,
	user_id VARCHAR(100) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(ID),
	FOREIGN KEY (item_update_id) REFERENCES item_updates(ID),
	UNIQUE (user_id, item_update_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);